version: "3.4"

services:
  switchboard: &switchboard
    image: nginx
    environment:
      - NGINX_PORT=80
    ports:
      - "8080:80"
    volumes:
#      - ./nginx_templates:/etc/nginx/templates
      - ./resources:/usr/share/nginx/html
    networks:
      - world
      - bubble

  debug-switchboard:
    <<: *switchboard
    command: ["nginx-debug", "-g", "daemon off;"]

networks:
  world:
    external: true
  bubble:
    internal: true